on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # Build the SERVER container 
        - name: 'Build and push SERVER image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./server/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:latest

      # Create the ENV for the FRONTEND
        - name: Create env file
          run: |
            touch .env
            echo REACT_APP_API_PROD=${{ REACT_APP_API_PROD }}>> .env
            echo REACT_APP_STORAGESASTOKEN=${{ REACT_APP_STORAGESASTOKEN }} >> .env
            echo REACT_APP_SECRET_TOKEN=${{ REACT_APP_SECRET_TOKEN }} >> .env
            cat .env
      # Build the FRONTEND  container 
        - name: 'Build and push FRONTEND image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./memeteca/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest

